project_name: pod-image-aging

builds:
  - main: ./cmd/
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

kos:
  - repository: hebestreit/pod-image-aging
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

release:
  github:
    owner: hebestreit
    name: pod-image-aging
