project_name: pod-image-aging

builds:
  - main: ./cmd/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

dockers:
  - image_templates:
      - "hebestreit/pod-image-aging:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "hebestreit/pod-image-aging:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "hebestreit/pod-image-aging:{{ .Tag }}"
    image_templates:
      - "hebestreit/pod-image-aging:{{ .Tag }}-amd64"
      - "hebestreit/pod-image-aging:{{ .Tag }}-arm64"

release:
  github:
    owner: hebestreit
    name: pod-image-aging
