apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pod-image-aging.fullname" . }}-leader-election-rolebinding
  labels:
      {{- include "pod-image-aging.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pod-image-aging.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "pod-image-aging.serviceAccountName" . }}
  namespace: {{ include "pod-image-aging.namespace" . }}
